trigger:
- main

pool:
  vmImage: 'windows-latest'


variables:
  buildConfiguration: 'Release'

steps:


- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.cipro'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'